workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: europe-docker.pkg.dev/vertex-ai/training/xgboost-cpu.1-1:latest
      packageUris: ["gs://aliz-ml-spec-2022/demo-2/package/trainer-0.1.tar.gz"]
      pythonModule: trainer.task
      args: [
        "--gamma", "0",
        "--subsample", "1",
        "--n_estimators", "100",
        "--learning_rate", "0.1",
        "--max_depth", "3"
        ]
